[package]
name = "libsalus"
version = "0.1.0"
authors = ["BooleanCat <tomgodkin@pm.me>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
jsonschema = "0.4"